dist: trusty
group: edge
language: php

addons:
  chrome: stable

php:
  - 7.1
  - 5.6

env:
  global:
    - PROJECT_NAME=contentacms
    - PROJECT_BUILD_PATH=$HOME/$PROJECT_NAME

branches:
  only:
    - 8.x-1.x
    - feature/91_Generate_GitHub_Releases

before_install:
  - nvm install 6.11.0
  - nvm use 6.11.0
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - mkdir $PROJECT_BUILD_PATH

install:
  - yarn install
  - composer run-script install-contenta $PROJECT_BUILD_PATH --timeout=0

before_script:
  - export DISPLAY=:99.0
  # Prevent chrome deadlock when running Nightwatch tests.
  # See https://stackoverflow.com/questions/41487659/nightwatch-selenium-socket-hang-up
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - composer run-script start-contenta $PROJECT_BUILD_PATH --timeout=0 &
  - sleep 5 # give web server some time to start

script:
  - yarn run nightwatch

after_script:
  - killall php

before_deploy:
  - "ls -la"
  - "pwd"
  - "export TAG_NAME=app_release-`date +%Y-%m-%d`_build_$TRAVIS_BUILD_NUMBER"
  - "zip -r $TAG_NAME.zip $PROJECT_BUILD_PATH"
  - "ls -la"
  - "echo \"$TRAVIS_TAG\""
  - "echo \"TAG_NAME\""
  - "export TRAVIS_TAG=${TRAVIS_TAG:-$TAG_NAME}"
  - "echo \"$TRAVIS_TAG\""

# Deploying GitHub Releases works only for tags, not for branches.
# Due to this issue we most tag every release that we wish to publish
deploy:
  provider: releases
  api_key:
    secure: Tq9CTZSNfP+A4lh4pZoB7yBW5tZqv9Um79/Ff7bekopUaam/FtLjxSREabamSKBvgTPwVNNPo/cY5wPnTNwkUGDogzuhN3Y+Quyeq3Sa/YNcANPVS9gQBkrCsnY0/htiTS6btC4SvKwz7Vosq+2+TZ1Q/bKGLejmM3mT6mQZyZuqYg83/2h8uuOr75bTeQvnFxbk4x7lsxYtcQ3gejKcmkC0a4dnF55Zi0ISvtic36EfRle94MxrHXzn7Z1cnMmb1+0GVKE9ffRLMd+/cR+oJLchS76uUzPeo8Oto+na7ke4klZVYMr2z7qyadH1hl3x41OY1wl68AlsOebfmdpVz63mefjyl/+Sl102DeXKIKoIiEyz4L5It+5/4pLy274Yy6TeLdnaP3uB9Y63Cy39+hXlGOMSOA24HG+fMZYaXFv8B9XcGqy2poDR2jRik+ypSJO6fsxJCfEFba+O/yKiY5Er8cWsWPdhYx7E/AIwXJh0xSLNOhnrA2jUUqgMjuwoI60PoKONxPzJUKDl1FBCBq1FZnFvAPADRX3x0FdPrqS5xy55g7u6cBj+7T9Xu9u0c7rvXGXUbJ77bxH5qJtuJUtJVQ4TGQ+XX04FdvrX7I/4JTjcspKpb8Swo7CIXEpUIpeYHIaU6ikGvxPPOfFXg73428wMRTXVmEF9bqcfuTg=
  file:
    - "$TAG_NAME.zip"
  skip_cleanup: true
  on:
    branch: feature/91_Generate_GitHub_Releases
    repo: contentacms/contenta_jsonapi
    php: 7.1
